enum Unit {
   F,
   C,
   K
};

struct Temp {
  long sensorId;
  double value;
  Unit unit;
};
struct Measurements {
  long deviceId;
  double humidity;
  double pressure;
  sequence<Temp,10> temperatures;
};
